#! /usr/bin/env bash

# Actual script directory path
DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" >/dev/null 2>&1 && pwd)"

# Process ID
PID=`ps -aux | grep -e "[w]arzonebot.py" | awk 'FNR == 1 {print $2}'`

if [ ! -z "$PID" ]; then
    echo "Already running."
    exit 1
fi

if [ ! -x $DIR/bin/activate ]; then
  echo "ERROR: install virtualenv into the current directory"
  exit 1
fi
. $DIR/bin/activate

# update and checkout last code
git pull -f
python3 -u $DIR/warzonebot.py

exit 0

